server:
  port: 10110
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.48.77:8848
        username: nacos
        password: nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'